name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'A username passed from the caller workflow'
        default: World
        required: true
        type: string
    outputs:
      current_time: ${{ jobs.reusable-job.current_time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current_time: ${{ steps.time.outputs.time }}
    steps:
       - name: Echo Hello
         run: bash echo "Hello ${{ inputs.who-to-greet }}"
       - name: Set time
         id: time
         run: bash echo "time=$(date)" >> "$GITHUB_OUTPUT"
