name: Reuse
on: [workflow_dispatch]
jobs:
  call_workflow:
    uses: './.github/workflows/reusable.yml'
    with: 
      who-to-greet: 'mkk'
  use_output:
    runs-on: ubuntu-latest
    needs: [call_workflow]
    steps:
    - name: Echo time
      run: bash echo "${{ needs.call_workflow.outputs.current_time }}"
