name: Main workflow
on: workflow_dispatch
jobs:
  call_workflow:
    uses: './.github/workflows/reusable.yml'
    with: 
      who-to-greet: 'mkk'
  use_output:
    runs-on: ubuntu-latest
    needs: [call_workflow]
    outputs:
      something: ${{ needs.call_workflow.outputs.current_time }}
    steps:
    - name: Echo time
      run: echo something
